//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarTBL()
        {
            this.ModTBLs = new HashSet<ModTBL>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string TopSpeed { get; set; }
        public string ZeroTo100 { get; set; }
        public string Horsepower { get; set; }
        public string Torque { get; set; }
        public string MaxRpm { get; set; }
        public string FuelMpg { get; set; }
        public string ImageUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModTBL> ModTBLs { get; set; }
    }
}
